#!/bin/bash

DEV=HDMI1
RESOLUTION="1920x1080"
OFFSET="1360x0"

function HDMIConnected { 
  ! xrandr | grep $DEV | grep disconnected
}

function EnableHDMI { 
 xrandr --output $DEV --mode $RESOLUTION --pos $OFFSET
}

function DisableHDMI { 
 xrandr --output $DEV --off
}

echo "cuban pete" >> "/home/pollo/hot.log"
if HDMIConnected 
then
  echo "enabling HDMI" 
  EnableHDMI
else 
  echo "disabling HDMI"
  DisableHDMI
fi
